definitions:
  golang-web-api_api_dtos.CityResponse:
    properties:
      country:
        $ref: '#/definitions/golang-web-api_api_dtos.CountryResponse'
      id:
        type: integer
      name:
        type: string
    type: object
  golang-web-api_api_dtos.CountryResponse:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  golang-web-api_api_dtos.CreateCityRequest:
    properties:
      countryId:
        type: integer
      name:
        maxLength: 20
        minLength: 3
        type: string
    required:
    - countryId
    - name
    type: object
  golang-web-api_api_dtos.CreateUpdateCountryRequest:
    properties:
      name:
        maxLength: 20
        minLength: 3
        type: string
    required:
    - name
    type: object
  golang-web-api_api_dtos.Filter:
    properties:
      filterType:
        description: text number
        type: string
      from:
        type: string
      to:
        type: string
      type:
        description: contains notContains equals notEqual startsWith lessThan lessThanOrEqual
          greaterThan greaterThanOrEqual inRange endsWith
        type: string
    type: object
  golang-web-api_api_dtos.GetOtpRequest:
    properties:
      mobileNumber:
        maxLength: 11
        minLength: 11
        type: string
    required:
    - mobileNumber
    type: object
  golang-web-api_api_dtos.PagedList-golang-web-api_api_dtos_CityResponse:
    properties:
      hasNextPage:
        type: boolean
      hasPreviousPage:
        type: boolean
      items:
        items:
          $ref: '#/definitions/golang-web-api_api_dtos.CityResponse'
        type: array
      pageNumber:
        type: integer
      totalPages:
        type: integer
      totalRows:
        type: integer
    type: object
  golang-web-api_api_dtos.PagedList-golang-web-api_api_dtos_CountryResponse:
    properties:
      hasNextPage:
        type: boolean
      hasPreviousPage:
        type: boolean
      items:
        items:
          $ref: '#/definitions/golang-web-api_api_dtos.CountryResponse'
        type: array
      pageNumber:
        type: integer
      totalPages:
        type: integer
      totalRows:
        type: integer
    type: object
  golang-web-api_api_dtos.PaginationInputWithFilter:
    properties:
      filter:
        additionalProperties:
          $ref: '#/definitions/golang-web-api_api_dtos.Filter'
        type: object
      pageNumber:
        type: integer
      pageSize:
        type: integer
      sort:
        items:
          $ref: '#/definitions/golang-web-api_api_dtos.Sort'
        type: array
    type: object
  golang-web-api_api_dtos.RefreshToken:
    properties:
      refreshToken:
        type: string
    required:
    - refreshToken
    type: object
  golang-web-api_api_dtos.RegisterLoginByMobileRequest:
    properties:
      mobileNumber:
        maxLength: 11
        minLength: 11
        type: string
      otp:
        maxLength: 6
        minLength: 6
        type: string
    required:
    - mobileNumber
    - otp
    type: object
  golang-web-api_api_dtos.Sort:
    properties:
      colId:
        type: string
      sort:
        type: string
    type: object
  golang-web-api_api_dtos.UpdateCityRequest:
    properties:
      countryId:
        type: integer
      name:
        maxLength: 20
        minLength: 3
        type: string
    type: object
  golang-web-api_api_helper.BaseHttpResponse:
    properties:
      error: {}
      result: {}
      resultCode:
        type: integer
      success:
        type: boolean
      validationErrors:
        items:
          $ref: '#/definitions/golang-web-api_api_helper.ValidationError'
        type: array
    type: object
  golang-web-api_api_helper.ValidationError:
    properties:
      message:
        type: string
      property:
        type: string
      tag:
        type: string
      value:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/cities/:
    post:
      consumes:
      - application/json
      description: Create a City
      parameters:
      - description: Create a City
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/golang-web-api_api_dtos.CreateCityRequest'
      responses:
        "201":
          description: City response
          schema:
            allOf:
            - $ref: '#/definitions/golang-web-api_api_helper.BaseHttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/golang-web-api_api_dtos.CityResponse'
              type: object
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/golang-web-api_api_helper.BaseHttpResponse'
      security:
      - AuthBearer: []
      summary: Create a City
      tags:
      - Cities
  /v1/cities/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a City
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: response
          schema:
            $ref: '#/definitions/golang-web-api_api_helper.BaseHttpResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/golang-web-api_api_helper.BaseHttpResponse'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/golang-web-api_api_helper.BaseHttpResponse'
      security:
      - AuthBearer: []
      summary: Delete a City
      tags:
      - Cities
    get:
      consumes:
      - application/json
      description: Get a City
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: City response
          schema:
            allOf:
            - $ref: '#/definitions/golang-web-api_api_helper.BaseHttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/golang-web-api_api_dtos.CityResponse'
              type: object
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/golang-web-api_api_helper.BaseHttpResponse'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/golang-web-api_api_helper.BaseHttpResponse'
      security:
      - AuthBearer: []
      summary: Get a City
      tags:
      - Cities
    put:
      consumes:
      - application/json
      description: Update a City
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: integer
      - description: Update a City
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/golang-web-api_api_dtos.UpdateCityRequest'
      responses:
        "200":
          description: City response
          schema:
            allOf:
            - $ref: '#/definitions/golang-web-api_api_helper.BaseHttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/golang-web-api_api_dtos.CityResponse'
              type: object
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/golang-web-api_api_helper.BaseHttpResponse'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/golang-web-api_api_helper.BaseHttpResponse'
      security:
      - AuthBearer: []
      summary: Update a City
      tags:
      - Cities
  /v1/cities/get-by-filter:
    post:
      consumes:
      - application/json
      description: Get Cities
      parameters:
      - description: Request
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/golang-web-api_api_dtos.PaginationInputWithFilter'
      responses:
        "200":
          description: City response
          schema:
            allOf:
            - $ref: '#/definitions/golang-web-api_api_helper.BaseHttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/golang-web-api_api_dtos.PagedList-golang-web-api_api_dtos_CityResponse'
              type: object
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/golang-web-api_api_helper.BaseHttpResponse'
      security:
      - AuthBearer: []
      summary: Get Cities
      tags:
      - Cities
  /v1/countries/:
    post:
      consumes:
      - application/json
      description: Create a country
      parameters:
      - description: Create a country
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/golang-web-api_api_dtos.CreateUpdateCountryRequest'
      responses:
        "201":
          description: Country response
          schema:
            allOf:
            - $ref: '#/definitions/golang-web-api_api_helper.BaseHttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/golang-web-api_api_dtos.CountryResponse'
              type: object
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/golang-web-api_api_helper.BaseHttpResponse'
      security:
      - AuthBearer: []
      summary: Create a country
      tags:
      - Countries
  /v1/countries/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a country
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: response
          schema:
            $ref: '#/definitions/golang-web-api_api_helper.BaseHttpResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/golang-web-api_api_helper.BaseHttpResponse'
      security:
      - AuthBearer: []
      summary: Delete a country
      tags:
      - Countries
    get:
      consumes:
      - application/json
      description: Get a country
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: Country response
          schema:
            allOf:
            - $ref: '#/definitions/golang-web-api_api_helper.BaseHttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/golang-web-api_api_dtos.CountryResponse'
              type: object
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/golang-web-api_api_helper.BaseHttpResponse'
      security:
      - AuthBearer: []
      summary: Get a country
      tags:
      - Countries
    put:
      consumes:
      - application/json
      description: Update a country
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: integer
      - description: Update a country
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/golang-web-api_api_dtos.CreateUpdateCountryRequest'
      responses:
        "200":
          description: Country response
          schema:
            allOf:
            - $ref: '#/definitions/golang-web-api_api_helper.BaseHttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/golang-web-api_api_dtos.CountryResponse'
              type: object
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/golang-web-api_api_helper.BaseHttpResponse'
      security:
      - AuthBearer: []
      summary: Update a country
      tags:
      - Countries
  /v1/countries/get-by-filter:
    post:
      consumes:
      - application/json
      description: Get Countries
      parameters:
      - description: Request
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/golang-web-api_api_dtos.PaginationInputWithFilter'
      responses:
        "200":
          description: Country response
          schema:
            allOf:
            - $ref: '#/definitions/golang-web-api_api_helper.BaseHttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/golang-web-api_api_dtos.PagedList-golang-web-api_api_dtos_CountryResponse'
              type: object
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/golang-web-api_api_helper.BaseHttpResponse'
      security:
      - AuthBearer: []
      summary: Get Countries
      tags:
      - Countries
  /v1/health/:
    get:
      consumes:
      - application/json
      description: Health Check
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/golang-web-api_api_helper.BaseHttpResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/golang-web-api_api_helper.BaseHttpResponse'
      summary: Health Check
      tags:
      - health
  /v1/users/login:
    post:
      consumes:
      - application/json
      description: RegisterLoginByMobileNumber
      parameters:
      - description: RegisterLoginByMobileRequest
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/golang-web-api_api_dtos.RegisterLoginByMobileRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Success
          schema:
            $ref: '#/definitions/golang-web-api_api_helper.BaseHttpResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/golang-web-api_api_helper.BaseHttpResponse'
        "409":
          description: Failed
          schema:
            $ref: '#/definitions/golang-web-api_api_helper.BaseHttpResponse'
      summary: RegisterLoginByMobileNumber
      tags:
      - Users
  /v1/users/refresh-token:
    post:
      consumes:
      - application/json
      description: RefreshToken
      parameters:
      - description: RefreshToken
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/golang-web-api_api_dtos.RefreshToken'
      produces:
      - application/json
      responses:
        "201":
          description: Success
          schema:
            $ref: '#/definitions/golang-web-api_api_helper.BaseHttpResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/golang-web-api_api_helper.BaseHttpResponse'
        "409":
          description: Failed
          schema:
            $ref: '#/definitions/golang-web-api_api_helper.BaseHttpResponse'
      summary: RefreshToken
      tags:
      - Users
  /v1/users/send-otp:
    post:
      consumes:
      - application/json
      description: Send otp to user
      parameters:
      - description: GetOtpRequest
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/golang-web-api_api_dtos.GetOtpRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Success
          schema:
            $ref: '#/definitions/golang-web-api_api_helper.BaseHttpResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/golang-web-api_api_helper.BaseHttpResponse'
        "409":
          description: Failed
          schema:
            $ref: '#/definitions/golang-web-api_api_helper.BaseHttpResponse'
      summary: Send otp to user
      tags:
      - Users
securityDefinitions:
  AuthBearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
