server:
  internalPort: 5000
  externalPort: 9000
  runMode: debug
redis:
  host: redis_container
  port: 6379
  password: password
  db: 0
  dialTimeout: 10
  readTimeout: 10
  writeTimeout: 10
  poolSize: 15
  poolTimeout: 10
postgres:
  host: postgres_container
  port: 5432
  user: postgres
  password: admin
  dbName: car_sale_db
  sslMode: disable
  maxIdleConns: 15
  maxOpenConns: 100
  connMaxLifetime: 5
cors:
  allowOrigins: "*"
logger:
  filePath: ../logs/
  encoding: json
  level: debug
  logger: zap
otp:
  expireTime: 120
  digits: 6
  limiter: 100
jwt:
  secret: "mySecretKey"
  refreshSecret: "mySecretKey"
  accessTokenExpireDuration: 1440
  refreshTokenExpireDuration: 60